[tool.poetry]
name = "erda"
version = "0.1.0"
description = ""
authors = ["yamasakih <yamasaki.phone@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
